HW4D5/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :update, :show, :destroy]
end

HW4D5/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  style      :string           default("Studio"), not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  belongs_to :band

  validates :title, :year, :style, :band_id, presence: true

  
end

HW4D5/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

HW4D5/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :password_digest, presence: true
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  #give our user a new session token
  #then save that new session token to the database
  #return the new session token
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

HW4D5/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    #I have to pass the band_id to the album as a hidden value in the field
    @band_id = params[:band_id]
    render :new
  end

  def create
    album = Album.new(album_params)

    if album.save
      redirect_to album_url(album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    album = Album.find_by(id: params[:id])
    if album.update(album_params)
      redirect_to album_url(album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :edit
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to band_url(album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :style, :band_id)
  end
end

HW4D5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  #Unsure why I need booleans instead of truthy and falsy values, will ask in class
  def logged_in?
    if current_user
      true
    else
      false
    end
  end


end

HW4D5/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def new
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to band_url(band)
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if band.update(band_params)
      redirect_to band_url(band)
    else
      flash.now[:errors] = band.errors.full_messages
      render :edit
    end
  end

  def destroy
    Band.destroy(params[:id])
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name)
  end

end

HW4D5/app/controllers/session_controller.rb
class SessionController < ApplicationController

  #For showing form to log in
  def new
  end

  #For logging in
  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    #If we found a valid user with that email and password,
    #Log in that user, then redirect to the show page for that user
    if user
      login!(user)
      redirect_to user_url(user)
    #Otherwise, go back to the log in page and add an error saying invalid username password combination
    else
      flash.now[:errors] = ["Invalid password and username combination"]
      render :new
    end
  end

  #For logging out
  def destroy
    logout!(current_user)
    redirect_to new_session_url
  end
end

HW4D5/app/controllers/users_controller.rb
class UsersController < ApplicationController

  #Form to create new user (Found in view, users/new.html.erb)
  def new

  end

  #Create the new user
  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      #will change url, but I get to maintain the data I already inputted on the form
      render :new
    end
  end

  #Show a specific user
  def show
    #Use the id wildcard in the url to find the user
    @user = User.find_by(id: params[:id])
    if @user
      render :show
      #if invalid wildcard :id
    else
      render json: "Come on amigo, this is not a valid user"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end


end

HW4D5/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'/>".html_safe
  end
end

HW4D5/app/views/bands/_band.html.erb
<p>Band Name: <%= band.name %> </p>

HW4D5/app/views/bands/_form.html.erb
<% if action == :edit %>
  <% url = band_url(band) %>
  <% submit_button_label = "Edit Band" %>
<% else  %>
  <% url = bands_url %>
  <% submit_button_label = "Create Band" %>
  <% band = Band.new %>
<% end %>

<form class="" action=" <%= url %> " method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end  %>
  <%= auth_token %>
  <label> Name
    <input type="text" name="band[name]" value=" <%= band.name %> ">
  </label>
  <input type="submit" name="" value=" <%= submit_button_label %> ">
  <%# if action == :edit %>
    <%#= button_to 'Delete Band', band_url(band), method: :delete %>
  <%# end  %>
</form>

HW4D5/app/views/bands/edit.html.erb
<%= render 'form', action: :edit, band: @band %> 

HW4D5/app/views/bands/index.html.erb
<%= render @bands %>

HW4D5/app/views/bands/new.html.erb
<%= render 'form', action: :new %> 

HW4D5/app/views/bands/show.html.erb
<p>Band Name: <%= @band.name %> </p>
<h1> Albums </h1>
<% albums = Album.where(band_id: @band.id) %>
<% albums.each do |album| %>
  <a class="band_show_a" href=" <%= album_url(album) %> "> <%= album.title %> </a>
  <br>
<% end %>
<%= button_to 'Create an Album', new_band_album_url(@band), method: :get %>

HW4D5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/errors' %>
    <%= yield %>
  </body>
</html>

HW4D5/app/views/session/new.html.erb
<form class="" action="<%= session_index_url %>" method="post">
  <%= auth_token %>
  <label> Email
    <input type="text" name="user[email]" value="">
  </label>
  <label> Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Log In">
</form>

HW4D5/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <p> <%= error %> </p>
  <% end %>
<% end %>

HW4D5/app/views/shared/_header.html.erb
<header>
  <h1> Music App </h1>
  <% if logged_in? %>
    <p> Hello: <%= current_user.email %> </p>
    <form class="log_out" action=" <%= session_url(current_user) %> " method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="Log Out">
    </form>
  <% else %>
    <a href=" <%= new_session_url %> "> Sign In </a>
    <a href=" <%= new_user_url %> "> Sign Up </a>
  <% end %>
</header>

HW4D5/app/views/users/new.html.erb
<form class="" action=" <%= users_url %> " method="post">
  <%= auth_token %>
  <label> Email
    <input type="text" name="user[email]" value="">
  </label>
  <label> Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Create a User">
</form>

HW4D5/app/views/users/show.html.erb
<p> User's email: <%= @user.email %> </p>